//
//  AcknowledgementCode.swift
//  MiClaro
//
//  Created by Roberto Gutierrez Resendiz on 23/08/17.
//  Copyright © 2017 am. All rights reserved.
//

import UIKit
import ObjectMapper

/// Clase relacionada con la definición del archivo de configuración
class AcknowledgementCode : NSObject, Mappable{

    var aSSCMACCMANASSACCBSERR0 : String?
    var aSSCMACCMANASSACCBSERR1 : String?
    var aSSCMACCMANASSACCBSERR2 : String?
    var aSSCMACCMANASSACCSC1 : String?
    var aSSCMACCMANASSACCTFERR0 : String?
    var aSSCMACCMANASSACCTFERR1 : String?
    var aSSCMACCMANASSACCTFERR2 : String?
    var aSSCMACCMANASSACCTFERR3 : String?
    var aSSCMACCMANASSACCTFERR4 : String?
    var aSSCMACCMANASSACCTFERR5 : String?
    var aSSCMACCMANASSACCTFERR6 : String?
    var aSSCMACCMANRETACCDETFERR0 : String?
    var aSSCMACCMANRETACCDETFERR1 : String?
    var aSSCMACCMANRETACCDETFERR2 : String?
    var aSSCMACCMANRETACCDETFERR3 : String?
    var aSSCMACCMANRETACCDETFERR4 : String?
    var aSSCMACCMANRETACCDETFERR5 : String?
    var aSSCMACCMANRETACCDETBSERR0 : String?
    var aSSCMACCMANRETACCDETBSERR3 : String?
    var aSSCMACCMANRETACCDETSC1 : String?
    var aSSCMACCMANRETACCDETTFERR4 : String?
    var aSSCMACCMANRETASSACCBSERR0 : String?
    var aSSCMACCMANRETASSACCBSERR2 : String?
    var aSSCMACCMANRETASSACCSC1 : String?
    var aSSCMACCMANRETASSACCTFERR0 : String?
    var aSSCMACCMANRETASSACCTFERR1 : String?
    var aSSCMACCMANRETASSACCTFERR2 : String?
    var aSSCMACCMANRETASSACCTFERR3 : String?
    var aSSCMACCMANRETASSACCTFERR4 : String?
    var aSSCMACCMANRETASSACCTFERR5 : String?
    var aSSCMACCMANRETASSACCTFERR6 : String?
    var aSSCMACCMANVALNUMBSERR0 : String?
    var aSSCMACCMANVALNUMBSERR1 : String?
    var aSSCMACCMANVALNUMSC1 : String?
    var aSSCMACCMANVALNUMTFERR0 : String?
    var aSSCMACCMANVALNUMTFERR1 : String?
    var aSSCMACCMANVALNUMTFERR2 : String?
    var aSSCMACCMANVALNUMTFERR3 : String?
    var aSSCMACCMANVALNUMTFERR4 : String?
    var aSSCMACCMANVALNUMTFERR5 : String?
    var aSSCMCUSMANRETPERVERQUEBSERR0 : String?
    var aSSCMCUSMANRETPERVERQUEBSERR1 : String?
    var aSSCMCUSMANRETPERVERQUEBSERR2 : String?
    var aSSCMCUSMANRETPERVERQUESC1 : String?
    var aSSCMCUSMANRETPERVERQUETFERR0 : String?
    var aSSCMCUSMANRETPERVERQUETFERR1 : String?
    var aSSCMCUSMANRETPERVERQUETFERR2 : String?
    var aSSCMCUSMANVALPERVERQUEBSERR0 : String?
    var aSSCMCUSMANVALPERVERQUEBSERR1 : String?
    var aSSCMCUSMANVALPERVERQUEBSERR2 : String?
    var aSSCMCUSMANVALPERVERQUEBSERR3 : String?
    var aSSCMCUSMANVALPERVERQUEBSERR4 : String?
    var aSSCMCUSMANVALPERVERQUEBSERR5 : String?
    var aSSCMCUSMANVALPERVERQUESC1 : String?
    var aSSCMCUSMANVALPERVERQUESC2 : String?
    var aSSCMCUSMANVALPERVERQUESC3 : String?
    var aSSCMCUSMANVALPERVERQUETFERR0 : String?
    var aSSCMCUSMANVALPERVERQUETFERR1 : String?
    var aSSCMCUSMANVALPERVERQUETFERR10 : String?
    var aSSCMCUSMANVALPERVERQUETFERR2 : String?
    var aSSCMCUSMANVALPERVERQUETFERR3 : String?
    var aSSCMCUSMANVALPERVERQUETFERR4 : String?
    var aSSCMCUSMANVALPERVERQUETFERR5 : String?
    var aSSCMCUSMANVALPERVERQUETFERR6 : String?
    var aSSCMCUSMANVALPERVERQUETFERR7 : String?
    var aSSCMCUSMANVALPERVERQUETFERR8 : String?
    var aSSCMCUSMANVALPERVERQUETFERR9 : String?
    var aSSCMIDEMANCRENEWREGBSERR0 : String?
    var aSSCMIDEMANCRENEWREGBSERR1 : String?
    var aSSCMIDEMANCRENEWREGBSERR2 : String?
    var aSSCMIDEMANCRENEWREGSC1 : String?
    var aSSCMIDEMANCRENEWREGTFERR0 : String?
    var aSSCMIDEMANCRENEWREGTFERR1 : String?
    var aSSCMIDEMANCRENEWREGTFERR2 : String?
    var aSSCMIDEMANCRENEWREGTFERR3 : String?
    var aSSCMIDEMANCRENEWREGTFERR5 : String?
    var aSSCMIDEMANGTMPPWDBSERR0 : String?
    var aSSCMIDEMANGTMPPWDBSERR1 : String?
    var aSSCMIDEMANGTMPPWDBSERR2 : String?
    var aSSCMIDEMANGTMPPWDBSERR3 : String?
    var aSSCMIDEMANGTMPPWDBSERR4 : String?
    var aSSCMIDEMANGTMPPWDBSERR5 : String?
    var aSSCMIDEMANGTMPPWDSC1 : String?
    var aSSCMIDEMANGTMPPWDTFERR0 : String?
    var aSSCMIDEMANGTMPPWDTFERR1 : String?
    var aSSCMIDEMANGTMPPWDTFERR2 : String?
    var aSSCMIDEMANGTMPPWDTFERR3 : String?
    var aSSCMIDEMANGTMPPWDTFERR4 : String?
    var aSSCMIDEMANGTMPPWDTFERR5 : String?
    var aSSCMIDEMANRETPROFINFBSERR0 : String?
    var aSSCMIDEMANRETPROFINFBSERR1 : String?
    var aSSCMIDEMANRETPROFINFSC1 : String?
    var aSSCMIDEMANRETPROFINFTFERR0 : String?
    var aSSCMIDEMANRETPROFINFTFERR1 : String?
    var aSSCMIDEMANRETPROFINFTFERR2 : String?
    var aSSCMIDEMANRETPROFINFTFERR3 : String?
    var aSSCMIDEMANRETPROFINFTFERR5 : String?
    var aSSCMIDEMANUPDPROINFBSERR0 : String?
    var aSSCMIDEMANUPDPROINFBSERR1 : String?
    var aSSCMIDEMANUPDPROINFBSERR2 : String?
    var aSSCMIDEMANUPDPROINFBSERR3 : String?
    var aSSCMIDEMANUPDPROINFBSERR4 : String?
    var aSSCMIDEMANUPDPROINFBSERR5 : String?
    var aSSCMIDEMANUPDPROINFBSERR6 : String?
    var aSSCMIDEMANUPDPROINFBSERR7 : String?
    var aSSCMIDEMANUPDPROINFBSERR8 : String?
    var aSSCMIDEMANUPDPROINFBSERR9 : String?
    var aSSCMIDEMANUPDPROINFSC1 : String?
    var aSSCMIDEMANUPDPROINFTFERR0 : String?
    var aSSCMIDEMANUPDPROINFTFERR1 : String?
    var aSSCMIDEMANUPDPROINFTFERR2 : String?
    var aSSCMIDEMANUPDPROINFTFERR3 : String?
    var aSSCMIDEMANUPDPROINFTFERR5 : String?
    var aSSCMIDEMANUPDPWDBSERR0 : String?
    var aSSCMIDEMANUPDPWDSC1 : String?
    var aSSCMIDEMANUPDPWDTFERR0 : String?
    var aSSCMIDEMANUPDPWDTFERR1 : String?
    var aSSCMIDEMANUPDPWDTFERR2 : String?
    var aSSCMIDEMANUPDPWDTFERR3 : String?
    var aSSCMIDEMANUPDPWDTFERR4 : String?
    var aSSCMIDEMANUPDPWDTFERR5 : String?
    var aSSCMIDEMANUPDPWDEDPRFTFERR1 : String?
    var aSSCMIDEMANUPDTRANSC0 : String?
    var aSSCMIDEMANUPDTRANSC1 : String?
    var aSSCMIDEMANUPDTRANTFERR0 : String?
    var aSSCMIDEMANUPDTRANTFERR1 : String?
    var aSSCMIDEMANUPDTRANTFERR2 : String?
    var aSSCMIDEMANUPDTRANTFERR3 : String?
    var aSSCMIDEMANUPDTRANTFERR5 : String?
    var aSSCMIDEMANVALCREDBSERR1 : String?
    var aSSCMIDEMANVALCREDBSERR2 : String?
    var aSSCMIDEMANVALCREDBSERR3 : String?
    var aSSCMIDEMANVALCREDBSERR4 : String?
    var aSSCMIDEMANVALCREDBSERR5 : String?
    var aSSCMIDEMANVALCREDBSERR6 : String?
    var aSSCMIDEMANVALCREDBSERR7 : String?
    var aSSCMIDEMANVALCREDBSERR8 : String?
    var aSSCMIDEMANVALCREDBSERR9 : String?
    var aSSCMIDEMANVALCREDSC0 : String?
    var aSSCMIDEMANVALCREDTFERR0 : String?
    var aSSCMIDEMANVALCREDTFERR3 : String?
    var aSSCMIDEMANVALCREDTFERR5 : String?
    var aSSCMIDEMANVALCREDWN1 : String?
    var aSSCMIDEMANVALCREDWN2 : String?
    var aSSCMIDEMANVALCREDWN3 : String?
    var aSSCMIDEMANVALCREDWN4 : String?
    var aSSCMIDEMANVALCREDWN5 : String?
    var aSSCMIDEMANVALTMPPWDBSERR : String?
    var aSSCMIDEMANVALTMPPWDBSERR0 : String?
    var aSSCMIDEMANVALTMPPWDBSERR1 : String?
    var aSSCMIDEMANVALTMPPWDBSERR2 : String?
    var aSSCMIDEMANVALTMPPWDBSERR3 : String?
    var aSSCMIDEMANVALTMPPWDSC1 : String?
    var aSSCMIDEMANVALTMPPWDTFERR0 : String?
    var aSSCMIDEMANVALTMPPWDTFERR1 : String?
    var aSSCMIDEMANVALTMPPWDTFERR2 : String?
    var aSSCMIDEMANVALTMPPWDTFERR3 : String?
    var aSSCMIDEMANVALTMPPWDTFERR4 : String?
    var aSSCMIDEMANVALTMPPWDTFERR5 : String?
    var aSSCMIDEMANVALTRANSC1 : String?
    var aSSCMIDEMANVALTRANSC2 : String?
    var aSSCMIDEMANVALTRANSC3 : String?
    var aSSCMIDEMANVALTRANTFERR0 : String?
    var aSSCMIDEMANVALTRANTFERR1 : String?
    var aSSCMIDEMANVALTRANTFERR2 : String?
    var aSSCMIDEMANVALTRANTFERR3 : String?
    var aSSCMIDEMANVALTRANTFERR5 : String?
    var bCMBILMANGETPAPLESBSERR0 : String?
    var bCMBILMANGETPAPLESSC1 : String?
    var bCMBILMANGETPAPLESTFERR0 : String?
    var bCMBILMANGETPAPLESTFERR1 : String?
    var bCMBILMANGETPAPLESTFERR2 : String?
    var bCMBILMANGETPAPLESTFERR3 : String?
    var bCMBILMANGETPAPLESTFERR4 : String?
    var bCMBILMANGETPAPLESTFERR5 : String?
    var bCMBILMANRETBILDETBSERR0 : String?
    var bCMBILMANRETBILDETBSERR1 : String?
    var bCMBILMANRETBILDETBSERR2 : String?
    var bCMBILMANRETBILDETBSERR3 : String?
    var bCMBILMANRETBILDETSC1 : String?
    var bCMBILMANRETBILDETTFERR0 : String?
    var bCMBILMANRETBILDETTFERR1 : String?
    var bCMBILMANRETBILDETTFERR2 : String?
    var bCMBILMANRETBILDETTFERR3 : String?
    var bCMBILMANRETBILDETTFERR4 : String?
    var bCMBILMANRETBILDETTFERR5 : String?
    var bCMBILMANRETBILHISLISBSERR0 : String?
    var bCMBILMANRETBILHISLISBSERR1 : String?
    var bCMBILMANRETBILHISLISSC1 : String?
    var bCMBILMANRETBILHISLISSC2 : String?
    var bCMBILMANRETBILHISLISTFERR0 : String?
    var bCMBILMANRETBILHISLISTFERR1 : String?
    var bCMBILMANRETBILHISLISTFERR2 : String?
    var bCMBILMANRETBILHISLISTFERR3 : String?
    var bCMBILMANRETBILHISLISTFERR5 : String?
    var bCMBILMANRETELECDOCPDFBSERR0 : String?
    var bCMBILMANRETELECDOCPDFBSERR1 : String?
    var bCMBILMANRETELECDOCPDFBSERR2 : String?
    var bCMBILMANRETELECDOCPDFBSERR3 : String?
    var bCMBILMANRETELECDOCPDFBSERR4 : String?
    var bCMBILMANRETELECDOCPDFSC1 : String?
    var bCMBILMANRETELECDOCPDFTFERR0 : String?
    var bCMBILMANRETELECDOCPDFTFERR1 : String?
    var bCMBILMANRETELECDOCPDFTFERR2 : String?
    var bCMBILMANRETELECDOCPDFTFERR3 : String?
    var bCMBILMANRETELECDOCPDFTFERR4 : String?
    var bCMBILMANRETELECDOCPDFTFERR5 : String?
    var bCMBILMANSETPAPLESBSERR0 : String?
    var bCMBILMANSETPAPLESSC1 : String?
    var bCMBILMANSETPAPLESTFERR0 : String?
    var bCMBILMANSETPAPLESTFERR1 : String?
    var bCMBILMANSETPAPLESTFERR2 : String?
    var bCMBILMANSETPAPLESTFERR3 : String?
    var bCMBILMANSETPAPLESTFERR4 : String?
    var bCMBILMANSETPAPLESTFERR5 : String?
    var bCMBILMANSNDBILLNOTBSERR0 : String?
    var bCMBILMANSNDBILLNOTBSERR1 : String?
    var bCMBILMANSNDBILLNOTBSERR2 : String?
    var bCMBILMANSNDBILLNOTSC1 : String?
    var bCMBILMANSNDBILLNOTTFERR0 : String?
    var bCMBILMANSNDBILLNOTTFERR1 : String?
    var bCMBILMANSNDBILLNOTTFERR2 : String?
    var bCMBILMANSNDBILLNOTTFERR3 : String?
    var bCMBILMANSNDBILLNOTTFERR4 : String?
    var bCMBILMANSNDBILLNOTTFERR5 : String?
    var bCMBILMANSNDBILLNOTTFERR6 : String?
    var bCMBILMANSNDBILLNOTTFERR7 : String?
    var bCMBILMANUPTVERBSERR0 : String?
    var fFCMBUSANAMANRETPROBSERR0 : String?
    var fFCMBUSANAMANRETPROSC1 : String?
    var fFCMBUSANAMANRETPROTFERR0 : String?
    var fFCMBUSANAMANRETPROTFERR1 : String?
    var fFCMBUSANAMANRETPROTFERR2 : String?
    var fFCMBUSANAMANRETPROTFERR3 : String?
    var fFCMBUSANAMANRETPROTFERR4 : String?
    var fFCMBUSANAMANRETPROTFERR5 : String?
    var fFCMNOTMANSENNOTSC1 : String?
    var fFCMNOTMANSNDNOTBSERR0 : String?
    var fFCMNOTMANSNDNOTTFERR0 : String?
    var fFCMNOTMANSNDNOTTFERR2 : String?
    var fFCMNOTMANSNDNOTTFERR3 : String?
    var fFCMNOTMANSNDNOTTFERR5 : String?
    var fFCMSERMANRETCONDETINFBSERR0 : String?
    var fFCMSERMANRETCONDETINFTFERR0 : String?
    var fFCMSERMANRETPLABSERR0 : String?
    var fFCMSERMANRETPLABSERR1 : String?
    var fFCMSERMANRETPLABSERR2 : String?
    var fFCMSERMANRETPLASC1 : String?
    var fFCMSERMANRETPLATFERR0 : String?
    var fFCMSERMANRETPLATFERR1 : String?
    var fFCMSERMANRETPLATFERR2 : String?
    var fFCMSERMANRETPLATFERR3 : String?
    var fFCMSERMANRETPLATFERR4 : String?
    var fFCMSERMANRETPLATFERR5 : String?
    var fFCMSERMANRETRECOPTBSERR0 : String?
    var fFCMSERMANRETRECOPTBSERR1 : String?
    var fFCMSERMANRETRECOPTSC1 : String?
    var fFCMSERMANRETRECOPTTFERR0 : String?
    var fFCMSERMANRETRECOPTTFERR1 : String?
    var fFCMSERMANRETRECOPTTFERR2 : String?
    var fFCMSERMANRETRECOPTTFERR3 : String?
    var fFCMSERMANRETRECOPTTFERR4 : String?
    var fFCMSERMANRETRECOPTTFERR5 : String?
    var oSRCMNOTMANSENNOTBSERR0 : String?
    var oSRCMNOTMANSENNOTBSERR1 : String?
    var oSRCMNOTMANSENNOTBSERR2 : String?
    var oSRCMNOTMANSENNOTSC1 : String?
    var oSRCMNOTMANSENNOTTFERR0 : String?
    var fFCMSERMANRETSUBSSC0 : String?
    var fFCMSERMANRETSUBSSC1 : String?
    var fFCMSERMANRETBKLTSTATSC1 : String?
    var fFCMSERMANADDNEWPACKBSERR0 : String?
    var fFCMSERMANADDNEWPACKBSERR1 : String?
    var fFCMSERMANADDNEWPACKSC1 : String?
    var fFCMSERMANADDNEWPACKTFERR0 : String?
    var fFCMSERMANADDNEWPACKTFERR1 : String?
    var fFCMSERMANADDNEWPACKTFERR3 : String?
    var fFCMSERMANADDNEWPACKTFERR5 : String?

    override init() {
    }

    /// Función encargada de mapear el JSON correspondiente
    /// - parameter Map: Objeto de tipo Map
    required init?(map: Map) {
        super.init()
    }

    /// Función encargada de mapear el JSON correspondiente
    /// - parameter Map: Objeto de tipo Map
    func mapping(map: Map)
    {
        aSSCMACCMANASSACCBSERR0 <- map["ASSCM-ACCMAN-ASSACC-BSERR-0"]
        aSSCMACCMANASSACCBSERR1 <- map["ASSCM-ACCMAN-ASSACC-BSERR-1"]
        aSSCMACCMANASSACCBSERR2 <- map["ASSCM-ACCMAN-ASSACC-BSERR-2"]
        aSSCMACCMANASSACCSC1 <- map["ASSCM-ACCMAN-ASSACC-SC-1"]
        aSSCMACCMANASSACCTFERR0 <- map["ASSCM-ACCMAN-ASSACC-TFERR-0"]
        aSSCMACCMANASSACCTFERR1 <- map["ASSCM-ACCMAN-ASSACC-TFERR-1"]
        aSSCMACCMANASSACCTFERR2 <- map["ASSCM-ACCMAN-ASSACC-TFERR-2"]
        aSSCMACCMANASSACCTFERR3 <- map["ASSCM-ACCMAN-ASSACC-TFERR-3"]
        aSSCMACCMANASSACCTFERR4 <- map["ASSCM-ACCMAN-ASSACC-TFERR-4"]
        aSSCMACCMANASSACCTFERR5 <- map["ASSCM-ACCMAN-ASSACC-TFERR-5"]
        aSSCMACCMANASSACCTFERR6 <- map["ASSCM-ACCMAN-ASSACC-TFERR-6"]
        aSSCMACCMANRETACCDETFERR0 <- map["ASSCM-ACCMAN-RETACCDE-TFERR-0"]
        aSSCMACCMANRETACCDETFERR1 <- map["ASSCM-ACCMAN-RETACCDE-TFERR-1"]
        aSSCMACCMANRETACCDETFERR2 <- map["ASSCM-ACCMAN-RETACCDE-TFERR-2"]
        aSSCMACCMANRETACCDETFERR3 <- map["ASSCM-ACCMAN-RETACCDE-TFERR-3"]
        aSSCMACCMANRETACCDETFERR4 <- map["ASSCM-ACCMAN-RETACCDE-TFERR-4"]
        aSSCMACCMANRETACCDETFERR5 <- map["ASSCM-ACCMAN-RETACCDE-TFERR-5"]
        aSSCMACCMANRETACCDETBSERR0 <- map["ASSCM-ACCMAN-RETACCDET-BSERR-0"]
        aSSCMACCMANRETACCDETBSERR3 <- map["ASSCM-ACCMAN-RETACCDET-BSERR-3"]
        aSSCMACCMANRETACCDETSC1 <- map["ASSCM-ACCMAN-RETACCDET-SC-1"]
        aSSCMACCMANRETACCDETTFERR4 <- map["ASSCM-ACCMAN-RETACCDET-TFERR-4"]
        aSSCMACCMANRETASSACCBSERR0 <- map["ASSCM-ACCMAN-RETASSACC-BSERR-0"]
        aSSCMACCMANRETASSACCBSERR2 <- map["ASSCM-ACCMAN-RETASSACC-BSERR-2"]
        aSSCMACCMANRETASSACCSC1 <- map["ASSCM-ACCMAN-RETASSACC-SC-1"]
        aSSCMACCMANRETASSACCTFERR0 <- map["ASSCM-ACCMAN-RETASSACC-TFERR-0"]
        aSSCMACCMANRETASSACCTFERR1 <- map["ASSCM-ACCMAN-RETASSACC-TFERR-1"]
        aSSCMACCMANRETASSACCTFERR2 <- map["ASSCM-ACCMAN-RETASSACC-TFERR-2"]
        aSSCMACCMANRETASSACCTFERR3 <- map["ASSCM-ACCMAN-RETASSACC-TFERR-3"]
        aSSCMACCMANRETASSACCTFERR4 <- map["ASSCM-ACCMAN-RETASSACC-TFERR-4"]
        aSSCMACCMANRETASSACCTFERR5 <- map["ASSCM-ACCMAN-RETASSACC-TFERR-5"]
        aSSCMACCMANRETASSACCTFERR6 <- map["ASSCM-ACCMAN-RETASSACC-TFERR-6"]
        aSSCMACCMANVALNUMBSERR0 <- map["ASSCM-ACCMAN-VALNUM-BSERR-0"]
        aSSCMACCMANVALNUMBSERR1 <- map["ASSCM-ACCMAN-VALNUM-BSERR-1"]
        aSSCMACCMANVALNUMSC1 <- map["ASSCM-ACCMAN-VALNUM-SC-1"]
        aSSCMACCMANVALNUMTFERR0 <- map["ASSCM-ACCMAN-VALNUM-TFERR-0"]
        aSSCMACCMANVALNUMTFERR1 <- map["ASSCM-ACCMAN-VALNUM-TFERR-1"]
        aSSCMACCMANVALNUMTFERR2 <- map["ASSCM-ACCMAN-VALNUM-TFERR-2"]
        aSSCMACCMANVALNUMTFERR3 <- map["ASSCM-ACCMAN-VALNUM-TFERR-3"]
        aSSCMACCMANVALNUMTFERR4 <- map["ASSCM-ACCMAN-VALNUM-TFERR-4"]
        aSSCMACCMANVALNUMTFERR5 <- map["ASSCM-ACCMAN-VALNUM-TFERR-5"]
        aSSCMCUSMANRETPERVERQUEBSERR0 <- map["ASSCM-CUSMAN-RETPERVERQUE-BSERR-0"]
        aSSCMCUSMANRETPERVERQUEBSERR1 <- map["ASSCM-CUSMAN-RETPERVERQUE-BSERR-1"]
        aSSCMCUSMANRETPERVERQUEBSERR2 <- map["ASSCM-CUSMAN-RETPERVERQUE-BSERR-2"]
        aSSCMCUSMANRETPERVERQUESC1 <- map["ASSCM-CUSMAN-RETPERVERQUE-SC-1"]
        aSSCMCUSMANRETPERVERQUETFERR0 <- map["ASSCM-CUSMAN-RETPERVERQUE-TFERR-0"]
        aSSCMCUSMANRETPERVERQUETFERR1 <- map["ASSCM-CUSMAN-RETPERVERQUE-TFERR-1"]
        aSSCMCUSMANRETPERVERQUETFERR2 <- map["ASSCM-CUSMAN-RETPERVERQUE-TFERR-2"]
        aSSCMCUSMANVALPERVERQUEBSERR0 <- map["ASSCM-CUSMAN-VALPERVERQUE-BSERR-0"]
        aSSCMCUSMANVALPERVERQUEBSERR1 <- map["ASSCM-CUSMAN-VALPERVERQUE-BSERR-1"]
        aSSCMCUSMANVALPERVERQUEBSERR2 <- map["ASSCM-CUSMAN-VALPERVERQUE-BSERR-2"]
        aSSCMCUSMANVALPERVERQUEBSERR3 <- map["ASSCM-CUSMAN-VALPERVERQUE-BSERR-3"]
        aSSCMCUSMANVALPERVERQUEBSERR4 <- map["ASSCM-CUSMAN-VALPERVERQUE-BSERR-4"]
        aSSCMCUSMANVALPERVERQUEBSERR5 <- map["ASSCM-CUSMAN-VALPERVERQUE-BSERR-5"]
        aSSCMCUSMANVALPERVERQUESC1 <- map["ASSCM-CUSMAN-VALPERVERQUE-SC-1"]
        aSSCMCUSMANVALPERVERQUESC2 <- map["ASSCM-CUSMAN-VALPERVERQUE-SC-2"]
        aSSCMCUSMANVALPERVERQUESC3 <- map["ASSCM-CUSMAN-VALPERVERQUE-SC-3"]
        aSSCMCUSMANVALPERVERQUETFERR0 <- map["ASSCM-CUSMAN-VALPERVERQUE-TFERR-0"]
        aSSCMCUSMANVALPERVERQUETFERR1 <- map["ASSCM-CUSMAN-VALPERVERQUE-TFERR-1"]
        aSSCMCUSMANVALPERVERQUETFERR10 <- map["ASSCM-CUSMAN-VALPERVERQUE-TFERR-10"]
        aSSCMCUSMANVALPERVERQUETFERR2 <- map["ASSCM-CUSMAN-VALPERVERQUE-TFERR-2"]
        aSSCMCUSMANVALPERVERQUETFERR3 <- map["ASSCM-CUSMAN-VALPERVERQUE-TFERR-3"]
        aSSCMCUSMANVALPERVERQUETFERR4 <- map["ASSCM-CUSMAN-VALPERVERQUE-TFERR-4"]
        aSSCMCUSMANVALPERVERQUETFERR5 <- map["ASSCM-CUSMAN-VALPERVERQUE-TFERR-5"]
        aSSCMCUSMANVALPERVERQUETFERR6 <- map["ASSCM-CUSMAN-VALPERVERQUE-TFERR-6"]
        aSSCMCUSMANVALPERVERQUETFERR7 <- map["ASSCM-CUSMAN-VALPERVERQUE-TFERR-7"]
        aSSCMCUSMANVALPERVERQUETFERR8 <- map["ASSCM-CUSMAN-VALPERVERQUE-TFERR-8"]
        aSSCMCUSMANVALPERVERQUETFERR9 <- map["ASSCM-CUSMAN-VALPERVERQUE-TFERR-9"]
        aSSCMIDEMANCRENEWREGBSERR0 <- map["ASSCM-IDEMAN-CRENEWREG-BSERR-0"]
        aSSCMIDEMANCRENEWREGBSERR1 <- map["ASSCM-IDEMAN-CRENEWREG-BSERR-1"]
        aSSCMIDEMANCRENEWREGBSERR2 <- map["ASSCM-IDEMAN-CRENEWREG-BSERR-2"]
        aSSCMIDEMANCRENEWREGSC1 <- map["ASSCM-IDEMAN-CRENEWREG-SC-1"]
        aSSCMIDEMANCRENEWREGTFERR0 <- map["ASSCM-IDEMAN-CRENEWREG-TFERR-0"]
        aSSCMIDEMANCRENEWREGTFERR1 <- map["ASSCM-IDEMAN-CRENEWREG-TFERR-1"]
        aSSCMIDEMANCRENEWREGTFERR2 <- map["ASSCM-IDEMAN-CRENEWREG-TFERR-2"]
        aSSCMIDEMANCRENEWREGTFERR3 <- map["ASSCM-IDEMAN-CRENEWREG-TFERR-3"]
        aSSCMIDEMANCRENEWREGTFERR5 <- map["ASSCM-IDEMAN-CRENEWREG-TFERR-5"]
        aSSCMIDEMANGTMPPWDBSERR0 <- map["ASSCM-IDEMAN-GTMPPWD-BSERR-0"]
        aSSCMIDEMANGTMPPWDBSERR1 <- map["ASSCM-IDEMAN-GTMPPWD-BSERR-1"]
        aSSCMIDEMANGTMPPWDBSERR2 <- map["ASSCM-IDEMAN-GTMPPWD-BSERR-2"]
        aSSCMIDEMANGTMPPWDBSERR3 <- map["ASSCM-IDEMAN-GTMPPWD-BSERR-3"]
        aSSCMIDEMANGTMPPWDBSERR4 <- map["ASSCM-IDEMAN-GTMPPWD-BSERR-4"]
        aSSCMIDEMANGTMPPWDBSERR5 <- map["ASSCM-IDEMAN-GTMPPWD-BSERR-5"]
        aSSCMIDEMANGTMPPWDSC1 <- map["ASSCM-IDEMAN-GTMPPWD-SC-1"]
        aSSCMIDEMANGTMPPWDTFERR0 <- map["ASSCM-IDEMAN-GTMPPWD-TFERR-0"]
        aSSCMIDEMANGTMPPWDTFERR1 <- map["ASSCM-IDEMAN-GTMPPWD-TFERR-1"]
        aSSCMIDEMANGTMPPWDTFERR2 <- map["ASSCM-IDEMAN-GTMPPWD-TFERR-2"]
        aSSCMIDEMANGTMPPWDTFERR3 <- map["ASSCM-IDEMAN-GTMPPWD-TFERR-3"]
        aSSCMIDEMANGTMPPWDTFERR4 <- map["ASSCM-IDEMAN-GTMPPWD-TFERR-4"]
        aSSCMIDEMANGTMPPWDTFERR5 <- map["ASSCM-IDEMAN-GTMPPWD-TFERR-5"]
        aSSCMIDEMANRETPROFINFBSERR0 <- map["ASSCM-IDEMAN-RETPROFINF-BSERR-0"]
        aSSCMIDEMANRETPROFINFBSERR1 <- map["ASSCM-IDEMAN-RETPROFINF-BSERR-1"]
        aSSCMIDEMANRETPROFINFSC1 <- map["ASSCM-IDEMAN-RETPROFINF-SC-1"]
        aSSCMIDEMANRETPROFINFTFERR0 <- map["ASSCM-IDEMAN-RETPROFINF-TFERR-0"]
        aSSCMIDEMANRETPROFINFTFERR1 <- map["ASSCM-IDEMAN-RETPROFINF-TFERR-1"]
        aSSCMIDEMANRETPROFINFTFERR2 <- map["ASSCM-IDEMAN-RETPROFINF-TFERR-2"]
        aSSCMIDEMANRETPROFINFTFERR3 <- map["ASSCM-IDEMAN-RETPROFINF-TFERR-3"]
        aSSCMIDEMANRETPROFINFTFERR5 <- map["ASSCM-IDEMAN-RETPROFINF-TFERR-5"]
        aSSCMIDEMANUPDPROINFBSERR0 <- map["ASSCM-IDEMAN-UPDPROINF-BSERR-0"]
        aSSCMIDEMANUPDPROINFBSERR1 <- map["ASSCM-IDEMAN-UPDPROINF-BSERR-1"]
        aSSCMIDEMANUPDPROINFBSERR2 <- map["ASSCM-IDEMAN-UPDPROINF-BSERR-2"]
        aSSCMIDEMANUPDPROINFBSERR3 <- map["ASSCM-IDEMAN-UPDPROINF-BSERR-3"]
        aSSCMIDEMANUPDPROINFBSERR4 <- map["ASSCM-IDEMAN-UPDPROINF-BSERR-4"]
        aSSCMIDEMANUPDPROINFBSERR5 <- map["ASSCM-IDEMAN-UPDPROINF-BSERR-5"]
        aSSCMIDEMANUPDPROINFBSERR6 <- map["ASSCM-IDEMAN-UPDPROINF-BSERR-6"]
        aSSCMIDEMANUPDPROINFBSERR7 <- map["ASSCM-IDEMAN-UPDPROINF-BSERR-7"]
        aSSCMIDEMANUPDPROINFBSERR8 <- map["ASSCM-IDEMAN-UPDPROINF-BSERR-8"]
        aSSCMIDEMANUPDPROINFBSERR9 <- map["ASSCM-IDEMAN-UPDPROINF-BSERR-9"]
        aSSCMIDEMANUPDPROINFSC1 <- map["ASSCM-IDEMAN-UPDPROINF-SC-1"]
        aSSCMIDEMANUPDPROINFTFERR0 <- map["ASSCM-IDEMAN-UPDPROINF-TFERR-0"]
        aSSCMIDEMANUPDPROINFTFERR1 <- map["ASSCM-IDEMAN-UPDPROINF-TFERR-1"]
        aSSCMIDEMANUPDPROINFTFERR2 <- map["ASSCM-IDEMAN-UPDPROINF-TFERR-2"]
        aSSCMIDEMANUPDPROINFTFERR3 <- map["ASSCM-IDEMAN-UPDPROINF-TFERR-3"]
        aSSCMIDEMANUPDPROINFTFERR5 <- map["ASSCM-IDEMAN-UPDPROINF-TFERR-5"]
        aSSCMIDEMANUPDPWDBSERR0 <- map["ASSCM-IDEMAN-UPDPWD-BSERR-0"]
        aSSCMIDEMANUPDPWDSC1 <- map["ASSCM-IDEMAN-UPDPWD-SC-1"]
        aSSCMIDEMANUPDPWDTFERR0 <- map["ASSCM-IDEMAN-UPDPWD-TFERR-0"]
        aSSCMIDEMANUPDPWDTFERR1 <- map["ASSCM-IDEMAN-UPDPWD-TFERR-1"]
        aSSCMIDEMANUPDPWDTFERR2 <- map["ASSCM-IDEMAN-UPDPWD-TFERR-2"]
        aSSCMIDEMANUPDPWDTFERR3 <- map["ASSCM-IDEMAN-UPDPWD-TFERR-3"]
        aSSCMIDEMANUPDPWDTFERR4 <- map["ASSCM-IDEMAN-UPDPWD-TFERR-4"]
        aSSCMIDEMANUPDPWDTFERR5 <- map["ASSCM-IDEMAN-UPDPWD-TFERR-5"]
        aSSCMIDEMANUPDPWDEDPRFTFERR1 <- map["ASSCM-IDEMAN-UPDPWDEDPRF-TFERR-1"]
        aSSCMIDEMANUPDTRANSC0 <- map["ASSCM-IDEMAN-UPDTRAN-SC-0"]
        aSSCMIDEMANUPDTRANSC1 <- map["ASSCM-IDEMAN-UPDTRAN-SC-1"]
        aSSCMIDEMANUPDTRANTFERR0 <- map["ASSCM-IDEMAN-UPDTRAN-TFERR-0"]
        aSSCMIDEMANUPDTRANTFERR1 <- map["ASSCM-IDEMAN-UPDTRAN-TFERR-1"]
        aSSCMIDEMANUPDTRANTFERR2 <- map["ASSCM-IDEMAN-UPDTRAN-TFERR-2"]
        aSSCMIDEMANUPDTRANTFERR3 <- map["ASSCM-IDEMAN-UPDTRAN-TFERR-3"]
        aSSCMIDEMANUPDTRANTFERR5 <- map["ASSCM-IDEMAN-UPDTRAN-TFERR-5"]
        aSSCMIDEMANVALCREDBSERR1 <- map["ASSCM-IDEMAN-VALCRED-BSERR-1"]
        aSSCMIDEMANVALCREDBSERR2 <- map["ASSCM-IDEMAN-VALCRED-BSERR-2"]
        aSSCMIDEMANVALCREDBSERR3 <- map["ASSCM-IDEMAN-VALCRED-BSERR-3"]
        aSSCMIDEMANVALCREDBSERR4 <- map["ASSCM-IDEMAN-VALCRED-BSERR-4"]
        aSSCMIDEMANVALCREDBSERR5 <- map["ASSCM-IDEMAN-VALCRED-BSERR-5"]
        aSSCMIDEMANVALCREDBSERR6 <- map["ASSCM-IDEMAN-VALCRED-BSERR-6"]
        aSSCMIDEMANVALCREDBSERR7 <- map["ASSCM-IDEMAN-VALCRED-BSERR-7"]
        aSSCMIDEMANVALCREDBSERR8 <- map["ASSCM-IDEMAN-VALCRED-BSERR-8"]
        aSSCMIDEMANVALCREDBSERR9 <- map["ASSCM-IDEMAN-VALCRED-BSERR-9"]
        aSSCMIDEMANVALCREDSC0 <- map["ASSCM-IDEMAN-VALCRED-SC-0"]
        aSSCMIDEMANVALCREDTFERR0 <- map["ASSCM-IDEMAN-VALCRED-TFERR-0"]
        aSSCMIDEMANVALCREDTFERR3 <- map["ASSCM-IDEMAN-VALCRED-TFERR-3"]
        aSSCMIDEMANVALCREDTFERR5 <- map["ASSCM-IDEMAN-VALCRED-TFERR-5"]
        aSSCMIDEMANVALCREDWN1 <- map["ASSCM-IDEMAN-VALCRED-WN-1"]
        aSSCMIDEMANVALCREDWN2 <- map["ASSCM-IDEMAN-VALCRED-WN-2"]
        aSSCMIDEMANVALCREDWN3 <- map["ASSCM-IDEMAN-VALCRED-WN-3"]
        aSSCMIDEMANVALCREDWN4 <- map["ASSCM-IDEMAN-VALCRED-WN-4"]
        aSSCMIDEMANVALCREDWN5 <- map["ASSCM-IDEMAN-VALCRED-WN-5"]
        aSSCMIDEMANVALTMPPWDBSERR <- map["ASSCM-IDEMAN-VALTMPPWD-BSERR-"]
        aSSCMIDEMANVALTMPPWDBSERR0 <- map["ASSCM-IDEMAN-VALTMPPWD-BSERR-0"]
        aSSCMIDEMANVALTMPPWDBSERR1 <- map["ASSCM-IDEMAN-VALTMPPWD-BSERR-1"]
        aSSCMIDEMANVALTMPPWDBSERR2 <- map["ASSCM-IDEMAN-VALTMPPWD-BSERR-2"]
        aSSCMIDEMANVALTMPPWDBSERR3 <- map["ASSCM-IDEMAN-VALTMPPWD-BSERR-3"]
        aSSCMIDEMANVALTMPPWDSC1 <- map["ASSCM-IDEMAN-VALTMPPWD-SC-1"]
        aSSCMIDEMANVALTMPPWDTFERR0 <- map["ASSCM-IDEMAN-VALTMPPWD-TFERR-0"]
        aSSCMIDEMANVALTMPPWDTFERR1 <- map["ASSCM-IDEMAN-VALTMPPWD-TFERR-1"]
        aSSCMIDEMANVALTMPPWDTFERR2 <- map["ASSCM-IDEMAN-VALTMPPWD-TFERR-2"]
        aSSCMIDEMANVALTMPPWDTFERR3 <- map["ASSCM-IDEMAN-VALTMPPWD-TFERR-3"]
        aSSCMIDEMANVALTMPPWDTFERR4 <- map["ASSCM-IDEMAN-VALTMPPWD-TFERR-4"]
        aSSCMIDEMANVALTMPPWDTFERR5 <- map["ASSCM-IDEMAN-VALTMPPWD-TFERR-5"]
        aSSCMIDEMANVALTRANSC1 <- map["ASSCM-IDEMAN-VALTRAN-SC-1"]
        aSSCMIDEMANVALTRANSC2 <- map["ASSCM-IDEMAN-VALTRAN-SC-2"]
        aSSCMIDEMANVALTRANSC3 <- map["ASSCM-IDEMAN-VALTRAN-SC-3"]
        aSSCMIDEMANVALTRANTFERR0 <- map["ASSCM-IDEMAN-VALTRAN-TFERR-0"]
        aSSCMIDEMANVALTRANTFERR1 <- map["ASSCM-IDEMAN-VALTRAN-TFERR-1"]
        aSSCMIDEMANVALTRANTFERR2 <- map["ASSCM-IDEMAN-VALTRAN-TFERR-2"]
        aSSCMIDEMANVALTRANTFERR3 <- map["ASSCM-IDEMAN-VALTRAN-TFERR-3"]
        aSSCMIDEMANVALTRANTFERR5 <- map["ASSCM-IDEMAN-VALTRAN-TFERR-5"]
        bCMBILMANGETPAPLESBSERR0 <- map["BCM-BILMAN-GETPAPLES-BSERR-0"]
        bCMBILMANGETPAPLESSC1 <- map["BCM-BILMAN-GETPAPLES-SC-1"]
        bCMBILMANGETPAPLESTFERR0 <- map["BCM-BILMAN-GETPAPLES-TFERR-0"]
        bCMBILMANGETPAPLESTFERR1 <- map["BCM-BILMAN-GETPAPLES-TFERR-1"]
        bCMBILMANGETPAPLESTFERR2 <- map["BCM-BILMAN-GETPAPLES-TFERR-2"]
        bCMBILMANGETPAPLESTFERR3 <- map["BCM-BILMAN-GETPAPLES-TFERR-3"]
        bCMBILMANGETPAPLESTFERR4 <- map["BCM-BILMAN-GETPAPLES-TFERR-4"]
        bCMBILMANGETPAPLESTFERR5 <- map["BCM-BILMAN-GETPAPLES-TFERR-5"]
        bCMBILMANRETBILDETBSERR0 <- map["BCM-BILMAN-RETBILDET-BSERR-0"]
        bCMBILMANRETBILDETBSERR1 <- map["BCM-BILMAN-RETBILDET-BSERR-1"]
        bCMBILMANRETBILDETBSERR2 <- map["BCM-BILMAN-RETBILDET-BSERR-2"]
        bCMBILMANRETBILDETBSERR3 <- map["BCM-BILMAN-RETBILDET-BSERR-3"]
        bCMBILMANRETBILDETSC1 <- map["BCM-BILMAN-RETBILDET-SC-1"]
        bCMBILMANRETBILDETTFERR0 <- map["BCM-BILMAN-RETBILDET-TFERR-0"]
        bCMBILMANRETBILDETTFERR1 <- map["BCM-BILMAN-RETBILDET-TFERR-1"]
        bCMBILMANRETBILDETTFERR2 <- map["BCM-BILMAN-RETBILDET-TFERR-2"]
        bCMBILMANRETBILDETTFERR3 <- map["BCM-BILMAN-RETBILDET-TFERR-3"]
        bCMBILMANRETBILDETTFERR4 <- map["BCM-BILMAN-RETBILDET-TFERR-4"]
        bCMBILMANRETBILDETTFERR5 <- map["BCM-BILMAN-RETBILDET-TFERR-5"]
        bCMBILMANRETBILHISLISBSERR0 <- map["BCM-BILMAN-RETBILHISLIS-BSERR-0"]
        bCMBILMANRETBILHISLISBSERR1 <- map["BCM-BILMAN-RETBILHISLIS-BSERR-1"]
        bCMBILMANRETBILHISLISSC1 <- map["BCM-BILMAN-RETBILHISLIS-SC-1"]
        bCMBILMANRETBILHISLISSC2 <- map["BCM-BILMAN-RETBILHISLIS-SC-2"]
        bCMBILMANRETBILHISLISTFERR0 <- map["BCM-BILMAN-RETBILHISLIS-TFERR-0"]
        bCMBILMANRETBILHISLISTFERR1 <- map["BCM-BILMAN-RETBILHISLIS-TFERR-1"]
        bCMBILMANRETBILHISLISTFERR2 <- map["BCM-BILMAN-RETBILHISLIS-TFERR-2"]
        bCMBILMANRETBILHISLISTFERR3 <- map["BCM-BILMAN-RETBILHISLIS-TFERR-3"]
        bCMBILMANRETBILHISLISTFERR5 <- map["BCM-BILMAN-RETBILHISLIS-TFERR-5"]
        bCMBILMANRETELECDOCPDFBSERR0 <- map["BCM-BILMAN-RETELECDOCPDF-BSERR-0"]
        bCMBILMANRETELECDOCPDFBSERR1 <- map["BCM-BILMAN-RETELECDOCPDF-BSERR-1"]
        bCMBILMANRETELECDOCPDFBSERR2 <- map["BCM-BILMAN-RETELECDOCPDF-BSERR-2"]
        bCMBILMANRETELECDOCPDFBSERR3 <- map["BCM-BILMAN-RETELECDOCPDF-BSERR-3"]
        bCMBILMANRETELECDOCPDFBSERR4 <- map["BCM-BILMAN-RETELECDOCPDF-BSERR-4"]
        bCMBILMANRETELECDOCPDFSC1 <- map["BCM-BILMAN-RETELECDOCPDF-SC-1"]
        bCMBILMANRETELECDOCPDFTFERR0 <- map["BCM-BILMAN-RETELECDOCPDF-TFERR-0"]
        bCMBILMANRETELECDOCPDFTFERR1 <- map["BCM-BILMAN-RETELECDOCPDF-TFERR-1"]
        bCMBILMANRETELECDOCPDFTFERR2 <- map["BCM-BILMAN-RETELECDOCPDF-TFERR-2"]
        bCMBILMANRETELECDOCPDFTFERR3 <- map["BCM-BILMAN-RETELECDOCPDF-TFERR-3"]
        bCMBILMANRETELECDOCPDFTFERR4 <- map["BCM-BILMAN-RETELECDOCPDF-TFERR-4"]
        bCMBILMANRETELECDOCPDFTFERR5 <- map["BCM-BILMAN-RETELECDOCPDF-TFERR-5"]
        bCMBILMANSETPAPLESBSERR0 <- map["BCM-BILMAN-SETPAPLES-BSERR-0"]
        bCMBILMANSETPAPLESSC1 <- map["BCM-BILMAN-SETPAPLES-SC-1"]
        bCMBILMANSETPAPLESTFERR0 <- map["BCM-BILMAN-SETPAPLES-TFERR-0"]
        bCMBILMANSETPAPLESTFERR1 <- map["BCM-BILMAN-SETPAPLES-TFERR-1"]
        bCMBILMANSETPAPLESTFERR2 <- map["BCM-BILMAN-SETPAPLES-TFERR-2"]
        bCMBILMANSETPAPLESTFERR3 <- map["BCM-BILMAN-SETPAPLES-TFERR-3"]
        bCMBILMANSETPAPLESTFERR4 <- map["BCM-BILMAN-SETPAPLES-TFERR-4"]
        bCMBILMANSETPAPLESTFERR5 <- map["BCM-BILMAN-SETPAPLES-TFERR-5"]
        bCMBILMANSNDBILLNOTBSERR0 <- map["BCM-BILMAN-SNDBILLNOT-BSERR-0"]
        bCMBILMANSNDBILLNOTBSERR1 <- map["BCM-BILMAN-SNDBILLNOT-BSERR-1"]
        bCMBILMANSNDBILLNOTBSERR2 <- map["BCM-BILMAN-SNDBILLNOT-BSERR-2"]
        bCMBILMANSNDBILLNOTSC1 <- map["BCM-BILMAN-SNDBILLNOT-SC-1"]
        bCMBILMANSNDBILLNOTTFERR0 <- map["BCM-BILMAN-SNDBILLNOT-TFERR-0"]
        bCMBILMANSNDBILLNOTTFERR1 <- map["BCM-BILMAN-SNDBILLNOT-TFERR-1"]
        bCMBILMANSNDBILLNOTTFERR2 <- map["BCM-BILMAN-SNDBILLNOT-TFERR-2"]
        bCMBILMANSNDBILLNOTTFERR3 <- map["BCM-BILMAN-SNDBILLNOT-TFERR-3"]
        bCMBILMANSNDBILLNOTTFERR4 <- map["BCM-BILMAN-SNDBILLNOT-TFERR-4"]
        bCMBILMANSNDBILLNOTTFERR5 <- map["BCM-BILMAN-SNDBILLNOT-TFERR-5"]
        bCMBILMANSNDBILLNOTTFERR6 <- map["BCM-BILMAN-SNDBILLNOT-TFERR-6"]
        bCMBILMANSNDBILLNOTTFERR7 <- map["BCM-BILMAN-SNDBILLNOT-TFERR-7"]
        bCMBILMANUPTVERBSERR0 <- map["BCM-BILMAN-UPTVER-BSERR-0"]
        fFCMBUSANAMANRETPROBSERR0 <- map["FFCM-BUSANAMAN-RETPRO-BSERR-0"]
        fFCMBUSANAMANRETPROSC1 <- map["FFCM-BUSANAMAN-RETPRO-SC-1"]
        fFCMBUSANAMANRETPROTFERR0 <- map["FFCM-BUSANAMAN-RETPRO-TFERR-0"]
        fFCMBUSANAMANRETPROTFERR1 <- map["FFCM-BUSANAMAN-RETPRO-TFERR-1"]
        fFCMBUSANAMANRETPROTFERR2 <- map["FFCM-BUSANAMAN-RETPRO-TFERR-2"]
        fFCMBUSANAMANRETPROTFERR3 <- map["FFCM-BUSANAMAN-RETPRO-TFERR-3"]
        fFCMBUSANAMANRETPROTFERR4 <- map["FFCM-BUSANAMAN-RETPRO-TFERR-4"]
        fFCMBUSANAMANRETPROTFERR5 <- map["FFCM-BUSANAMAN-RETPRO-TFERR-5"]
        fFCMNOTMANSENNOTSC1 <- map["FFCM-NOTMAN-SENNOT-SC-1"]
        fFCMNOTMANSNDNOTBSERR0 <- map["FFCM-NOTMAN-SNDNOT-BSERR-0"]
        fFCMNOTMANSNDNOTTFERR0 <- map["FFCM-NOTMAN-SNDNOT-TFERR-0"]
        fFCMNOTMANSNDNOTTFERR2 <- map["FFCM-NOTMAN-SNDNOT-TFERR-2"]
        fFCMNOTMANSNDNOTTFERR3 <- map["FFCM-NOTMAN-SNDNOT-TFERR-3"]
        fFCMNOTMANSNDNOTTFERR5 <- map["FFCM-NOTMAN-SNDNOT-TFERR-5"]
        fFCMSERMANRETCONDETINFBSERR0 <- map["FFCM-SERMAN-RETCONDETINF-BSERR-0"]
        fFCMSERMANRETCONDETINFTFERR0 <- map["FFCM-SERMAN-RETCONDETINF-TFERR-0"]
        fFCMSERMANRETPLABSERR0 <- map["FFCM-SERMAN-RETPLA-BSERR-0"]
        fFCMSERMANRETPLABSERR1 <- map["FFCM-SERMAN-RETPLA-BSERR-1"]
        fFCMSERMANRETPLABSERR2 <- map["FFCM-SERMAN-RETPLA-BSERR-2"]
        fFCMSERMANRETPLASC1 <- map["FFCM-SERMAN-RETPLA-SC-1"]
        fFCMSERMANRETPLATFERR0 <- map["FFCM-SERMAN-RETPLA-TFERR-0"]
        fFCMSERMANRETPLATFERR1 <- map["FFCM-SERMAN-RETPLA-TFERR-1"]
        fFCMSERMANRETPLATFERR2 <- map["FFCM-SERMAN-RETPLA-TFERR-2"]
        fFCMSERMANRETPLATFERR3 <- map["FFCM-SERMAN-RETPLA-TFERR-3"]
        fFCMSERMANRETPLATFERR4 <- map["FFCM-SERMAN-RETPLA-TFERR-4"]
        fFCMSERMANRETPLATFERR5 <- map["FFCM-SERMAN-RETPLA-TFERR-5"]
        fFCMSERMANRETRECOPTBSERR0 <- map["FFCM-SERMAN-RETRECOPT-BSERR-0"]
        fFCMSERMANRETRECOPTBSERR1 <- map["FFCM-SERMAN-RETRECOPT-BSERR-1"]
        fFCMSERMANRETRECOPTSC1 <- map["FFCM-SERMAN-RETRECOPT-SC-1"]
        fFCMSERMANRETRECOPTTFERR0 <- map["FFCM-SERMAN-RETRECOPT-TFERR-0"]
        fFCMSERMANRETRECOPTTFERR1 <- map["FFCM-SERMAN-RETRECOPT-TFERR-1"]
        fFCMSERMANRETRECOPTTFERR2 <- map["FFCM-SERMAN-RETRECOPT-TFERR-2"]
        fFCMSERMANRETRECOPTTFERR3 <- map["FFCM-SERMAN-RETRECOPT-TFERR-3"]
        fFCMSERMANRETRECOPTTFERR4 <- map["FFCM-SERMAN-RETRECOPT-TFERR-4"]
        fFCMSERMANRETRECOPTTFERR5 <- map["FFCM-SERMAN-RETRECOPT-TFERR-5"]
        oSRCMNOTMANSENNOTBSERR0 <- map["OSRCM-NOTMAN-SENNOT-BSERR-0"]
        oSRCMNOTMANSENNOTBSERR1 <- map["OSRCM-NOTMAN-SENNOT-BSERR-1"]
        oSRCMNOTMANSENNOTBSERR2 <- map["OSRCM-NOTMAN-SENNOT-BSERR-2"]
        oSRCMNOTMANSENNOTSC1 <- map["OSRCM-NOTMAN-SENNOT-SC-1"]
        oSRCMNOTMANSENNOTTFERR0 <- map["OSRCM-NOTMAN-SENNOT-TFERR-0"]
        fFCMSERMANRETSUBSSC0 <- map["FFCM-SERMAN-RETSUBS-SC-0"]
        fFCMSERMANRETSUBSSC1 <- map["FFCM-SERMAN-RETSUBS-SC-1"]
        fFCMSERMANRETBKLTSTATSC1 <- map["FFCM-SERMAN-RETBKLTSTAT-SC-1"]
        fFCMSERMANADDNEWPACKBSERR0 <- map["FFCM-SERMAN-ADDNEWPACK-BSERR-0"]
        fFCMSERMANADDNEWPACKBSERR1 <- map["FFCM-SERMAN-ADDNEWPACK-BSERR-1"]
        fFCMSERMANADDNEWPACKSC1 <- map["FFCM-SERMAN-ADDNEWPACK-SC-1"]
        fFCMSERMANADDNEWPACKTFERR0 <- map["FFCM-SERMAN-ADDNEWPACK-TFERR-0"]
        fFCMSERMANADDNEWPACKTFERR1 <- map["FFCM-SERMAN-ADDNEWPACK-TFERR-1"]
        fFCMSERMANADDNEWPACKTFERR3 <- map["FFCM-SERMAN-ADDNEWPACK-TFERR-3"]
        fFCMSERMANADDNEWPACKTFERR5 <- map["FFCM-SERMAN-ADDNEWPACK-TFERR-5"]
            }
}
